package/netperf: unbreak build with GCC 5.1
The default C standard changed with the new GCC version. This causes the
'inline' keyword semantics to change, which yields this build breakage:

    nettest_omni.o: In function `send_omni_inner':
    nettest_omni.c:(.text+0x5d63): undefined reference to `demo_interval_tick'
    nettest_omni.c:(.text+0x61fa): undefined reference to `demo_interval_tick'
    nettest_omni.c:(.text+0x69b7): undefined reference to `demo_interval_tick'
    nettest_omni.c:(.text+0x69c6): undefined reference to `demo_interval_tick'
    collect2: error: ld returned 1 exit status

Adding an explicit -std=gnu89 to the CFLAGS unbreaks the build.

Signed-off-by: Steven Noonan <steven@uplinklabs.net>